spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
#    root: ERROR OR off
    KpCoding:
      example:
        JournalApp: DEBUG

weather:
  api:
    key: 4885187653dde9e7bf749d78997bff56